spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:license_drop}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: update